#include "GLOBAL_STORAGE.h"
#include "antlr4-runtime.h"
#include "USLLexer.h"
#include "USLParser.h"
#include "Windows.h"
#include "USLBaseListener.h"
#include "USLBaseVisitor.h"
import SYMBOL_TABLE;
 USLLexer* STORARE::lexer;
 antlr4::CommonTokenStream* STORARE::tokens;
 USLParser* STORARE::parser;
 GLOBAL::SymbolTable* STORARE::symbol_table;